# Include warnings about missing documentation?
doc-warnings: True

# Include warnings about tests?
test-warnings: False

# tests stricktness
strictness: medium
max-line-length: 120

# autodetect dependencies?
autodetect: True

# paths to be ignored
ignore-paths:
    - docs
    - preupg/ui
    - setup.py
    - tests
ignore-patterns:
    - ^preupg/script_api.py$
