sudo: true

language: python
python:
    - 2.7

cache:
    apt: true
    pip: true

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get -y install libopenscap1 python-dev
    - sudo pip install urlgrabber requests ordered-set coverage nose
    - sudo pip -v install https://github.com/rhinstaller/pykickstart/archive/pykickstart-2.zip
install:
    - sudo pip install tox
script:
    - echo "[preupgrade-assistant]" > ~/preupgrade-assistant.conf
    - echo "home_directory_file=.preupgrade-dirs" >> ~/preupgrade-assistant.conf
    - echo "user_config_file=enabled\n\n" >> ~/preupgrade-assistant.conf
    - echo "[home-dirs]\n.config/\n.mozilla/\n" >> ~/preupgrade-assistant.conf
    - sed -i 's|^PREUPG_CONFIG_FILE.*|PREUPG_CONFIG_FILE = "/home/travis/preupgrade-assistant.conf" |' preup/settings.py
    - sudo tox --recreate
